name: Build and Push Docker Images

on:
  push:
    branches:
      - main   # executa apenas quando fizer push na branch main
  workflow_dispatch: # permite rodar manualmente

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do reposit√≥rio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Faz login no DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Configura o buildx para builds mais modernos
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build e push do Backend
      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nogarimpo-backend:latest

      # Build e push do Frontend
      # - name: Build and push Frontend Docker image
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./frontend
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/nogarimpo-frontend:latest